# Generated by Django 4.2.4 on 2023-08-22 00:35

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, unique=True, verbose_name='название альбома')),
                ('release_year', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1860, 'Первая в мире аудиозапись сделана в 1860 году. В нашем каталоге не может быть альбомов, выпущенных до этого времени!'), django.core.validators.MaxValueValidator(2024, 'В наш каталог мы сможем добавить только уже вышедший альбом, либо альбом, выпуск которого назначен на этот или следующий год.')], verbose_name='год выпуска')),
            ],
            options={
                'verbose_name': 'альбом',
                'verbose_name_plural': 'альбомы',
            },
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, unique=True, verbose_name='имя исполнителя/название группы')),
            ],
            options={
                'verbose_name': 'исполнитель',
                'verbose_name_plural': 'исполнители',
            },
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, verbose_name='название песни/трека')),
            ],
            options={
                'verbose_name': 'песня/трек',
                'verbose_name_plural': 'песни/треки',
            },
        ),
        migrations.CreateModel(
            name='TrackFromAlbum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_number', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(1, 'Номер песни/трека не может быть меньше 1.')], verbose_name='номер песни/трека в альбоме')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.album')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.track')),
            ],
            options={
                'verbose_name': 'номер песни/трека в альбоме',
                'verbose_name_plural': 'номера песен/треков в альбомах',
                'unique_together': {('album', 'track', 'track_number')},
            },
        ),
        migrations.AddField(
            model_name='track',
            name='albums',
            field=models.ManyToManyField(related_name='tracks', through='music.TrackFromAlbum', to='music.album', verbose_name='из альбома'),
        ),
        migrations.AddField(
            model_name='album',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albums', to='music.artist', verbose_name='исполнитель'),
        ),
    ]
